modoboa/modoboa-webmail

modoboa_webmail/static/modoboa_webmail/js/webmail.js
using the option to keep previous selection when selecting new items.
=> fix for #692

README.rst, modoboa_webmail/views.py
=> Compatibility fixes.

modoboa_webmail/forms.py, modoboa_webmail/handlers.py, modoboa_webmail/lib/imapemail.py, modoboa_webmail/lib/signature.py, modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/templates/modoboa_webmail/compose.html, modoboa_webmail/templates/modoboa_webmail/index.html, modoboa_webmail/tests.py, modoboa_webmail/views.py, test_project/test_project/settings.py
=> Added support for HTML signatures.

modoboa_webmail/forms.py, modoboa_webmail/lib/fetch_parser.py, modoboa_webmail/lib/imapemail.py, modoboa_webmail/lib/imapheader.py, modoboa_webmail/lib/imaputils.py, modoboa_webmail/static/modoboa_webmail/css/webmail.css, modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/templates/modoboa_webmail/compose.html, modoboa_webmail/templates/modoboa_webmail/headers.html, modoboa_webmail/templates/modoboa_webmail/index.html, modoboa_webmail/templatetags/webmail_tags.py, modoboa_webmail/views.py
=> Use contacts plugin if installed.

modoboa_webmail/forms.py, modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/templates/modoboa_webmail/compose.html, modoboa_webmail/tests.py, modoboa_webmail/validators.py, modoboa_webmail/views.py
=> Sender address selection.

modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/templatetags/webmail_tags.py, modoboa_webmail/urls.py, modoboa_webmail/views.py
=> Added 'mark as not spam' button.

modoboa_webmail/forms.py, modoboa_webmail/views.py
Forward of messages does not work. This is a fix proposal. With this changes, it works for me. The problem is that functions signatures might change but were not corrected in certains parts of the code...
Please check the fix is correct with an expert regard.
=> Fix forward of messages

modoboa_webmail/lib/imaputils.py, modoboa_webmail/static/modoboa_webmail/css/webmail.css, modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/templates/modoboa_webmail/email_list.html, modoboa_webmail/templatetags/webmail_tags.py
=> Added support for flagged messages.

modoboa_webmail/lib/imapemail.py, modoboa_webmail/templates/modoboa_webmail/headers.html, modoboa_webmail/templatetags/webmail_tags.py
=> Fixed several XSS issues.

modoboa_webmail/lib/imapemail.py
=> Use u'' prefix.

modoboa_webmail/lib/imapemail.py
=> Parse Reply-To header if present.

modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/templates/modoboa_webmail/compose.html, modoboa_webmail/validators.py
=> Replaced delimiter (, -> ;)

modoboa_webmail/lib/imapheader.py
=> Name can contain unsafe values.

modoboa_webmail/forms.py, modoboa_webmail/templates/modoboa_webmail/compose.html, modoboa_webmail/tests/data.py, modoboa_webmail/tests/test_views.py
=> Added missing headers.

modoboa_webmail/lib/imapemail.py, modoboa_webmail/tests/data.py, modoboa_webmail/tests/test_views.py, modoboa_webmail/views.py
=> Fixed empty email display

modoboa_webmail/constants.py, modoboa_webmail/lib/fetch_parser.py, modoboa_webmail/lib/utils.py, modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/templates/modoboa_webmail/main_action_bar.html, modoboa_webmail/templatetags/webmail_tags.py, modoboa_webmail/views.py
=> Added menu entries to sort messages.

modoboa_webmail/lib/imapheader.py
=> Use en as default date format.

modoboa_webmail/lib/imapemail.py
see #158 
Modoboa 1.10.5 will be required.
=> Fixed regression.

modoboa_webmail/templates/modoboa_webmail/headers.html, modoboa_webmail/templatetags/webmail_tags.py, modoboa_webmail/views.py
=> Encode url parameters.

modoboa_webmail/exceptions.py, modoboa_webmail/lib/imaputils.py, modoboa_webmail/static/modoboa_webmail/js/webmail.js, modoboa_webmail/tests/test_views.py
Few fixes in order to support share folders.
=> Added support for shared folders

.travis.yml, modoboa_webmail/lib/attachments.py, modoboa_webmail/tests/data.py, modoboa_webmail/tests/test_views.py, modoboa_webmail/views.py
=> Fixed email with attachments forwarding.

modoboa_webmail/lib/imaputils.py, test-requirements.txt
=> There can be more than one namespace per category.

modoboa_webmail/lib/attachments.py
=> Fixed attachment path.

modoboa_webmail/templates/modoboa_webmail/email_list.html, modoboa_webmail/templates/modoboa_webmail/headers.html
Fixed untruncated subject in the sent tab in webmail and Email Headers
=> Patch untruncated subject in the sent tab Update  email_list.html , and email header Update headers.html
